export const courses = [
  {
    id: 2,
    image: "/js.png",
    name: "Introduction to Javascript",
    description: "Learn Javascript FullStack",
    instructor: "HackYourFuture",
    price: "20.00",
    sellingprice: "10.00",
  },
  {
    id: 3,
    image: "/js.png",
    name: "Introduction to Javascript",
    description: "Learn Javascript FullStack",
    instructor: "Google",
    price: "20.00",
    sellingprice: "10.00",
  },
  {

    id: 4,
    image: "/js.png",
    name: "Introduction to Javascript",
    description: "Learn Javascript FullStack",
    instructor: "IBM",
    price: "20.00",
    sellingprice: "10.00",
  },
  {

    id: 5,
    image: "/js.png",
    name: "Introduction to Javascript",
    description: "Learn Javascript FullStack",
    instructor: "Meta",
    price: "20.00",
    sellingprice: "10.00",
  },
  {
    id: 6,
    image: "/js.png",
    name: "Introduction to Javascript",
    description: "Learn Javascript FullStack",
    instructor: "Meta",
    price: "20.00",
    sellingprice: "10.00",
  },
  {
    id: 7,
    image: "/js.png",
    name: "Introduction to Javascript",
    description: "Learn Javascript FullStack",
    instructor: "Meta",
    price: "20.00",
    sellingprice: "10.00",
  },
  {
    id: 8,
    image: "/js.png",
    name: "Introduction to Javascript",
    description: "Learn Javascript FullStack",
    instructor: "Meta",
    price: "20.00",
    sellingprice: "10.00",
  },
  {
    id: 9,
    image: "/js.png",
    name: "Introduction to Javascript",
    description: "Learn Javascript FullStack",
    instructor: "Meta",
    price: "20.00",
    sellingprice: "10.00",
  },
];
